GRANT ALL PRIVILEGES ON DATABASE plants_db TO docker_user;

create table location
(
    id   integer generated by default as identity
        primary key,
    name varchar not null
        unique
);

alter table location
    owner to docker_user;

create table if not exists plant
(
    id          integer generated by default as identity
        primary key,
    name        varchar not null,
    rareness    varchar not null,
    difficult   integer,
    feature     varchar not null,
    description varchar not null
);

alter table plant
    owner to docker_user;

create table if not exists plant_location
(
    plant_id    integer not null
        references plant,
    location_id integer not null
        references location
            on delete cascade,
    primary key (plant_id, location_id)
);

alter table plant_location
    owner to docker_user;

create table if not exists user_table
(
    id       integer generated by default as identity
        primary key,
    username varchar(100) not null
        unique,
    password varchar      not null,
    role     varchar      not null
);

alter table user_table
    owner to docker_user;
